doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '15'
                charset: utf8
                logging: '%kernel.debug%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
                options:
                    1002: 'SET search_path TO quiz_app,public'
                # PostgreSQL-specific configuration
                schema_filter: ~
                mapping_types:
                    enum: string
                    jsonb: json
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            # User Domain
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/ORM/Entity'
                prefix: 'App\User\Infrastructure\Persistence\Doctrine\ORM\Entity'
                alias: User
            # Quiz Domain
            Quiz:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Quiz/Infrastructure/Persistence/Doctrine/ORM/Entity'
                prefix: 'App\Quiz\Infrastructure\Persistence\Doctrine\ORM\Entity'
                alias: Quiz
            # Legacy entities (temporary for migration)
            Legacy:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: Legacy
        controller_resolver:
            auto_mapping: false
        # PostgreSQL-specific features
        dql:
            string_functions:
                JSONB_EXTRACT_TEXT: App\Shared\Infrastructure\Doctrine\DQL\JsonbExtractText
                CAST: Oro\ORM\Query\AST\Functions\Cast
            datetime_functions:
                DAY: Oro\ORM\Query\AST\Functions\SimpleFunction
                YEAR: Oro\ORM\Query\AST\Functions\SimpleFunction
                MONTH: Oro\ORM\Query\AST\Functions\SimpleFunction

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
