# Mercure Configuration
mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: ['*']  # Allow publishing to all topics
                subscribe: ['*']  # Allow subscribing to all topics