# Redis Configuration for Quiz Application
# Comprehensive Redis setup with multiple databases and connection pools

parameters:
    redis.host: '%env(REDIS_HOST)%'
    redis.port: '%env(int:REDIS_PORT)%'
    redis.password: '%env(REDIS_PASSWORD)%'
    redis.cluster_enabled: '%env(bool:REDIS_CLUSTER_ENABLED)%'
    redis.sentinel_enabled: '%env(bool:REDIS_SENTINEL_ENABLED)%'

when@dev:
    framework:
        cache:
            app: cache.adapter.filesystem
            pools:
                quiz.sessions:
                    adapter: cache.adapter.filesystem
                quiz.questions:
                    adapter: cache.adapter.filesystem
                analytics.user:
                    adapter: cache.adapter.filesystem
                analytics.leaderboard:
                    adapter: cache.adapter.filesystem
                app.config:
                    adapter: cache.adapter.filesystem
                analytics.realtime:
                    adapter: cache.adapter.filesystem
                app.fragments:
                    adapter: cache.adapter.filesystem
                cqrs.queries:
                    adapter: cache.adapter.filesystem

when@prod:
    framework:
        cache:
            # Main application cache
            app: cache.adapter.redis
            default_redis_provider: 'redis://app'
            
            # Specialized cache pools for different purposes
            pools:
                # Quiz session cache - 15-30 minutes TTL
                quiz.sessions:
                    adapter: cache.adapter.redis
                    provider: 'redis://sessions'
                    default_lifetime: 1800 # 30 minutes
                    
                # Questions and answers - 1 hour TTL
                quiz.questions:
                    adapter: cache.adapter.redis
                    provider: 'redis://questions'
                    default_lifetime: 3600 # 1 hour
                    
                # User analytics - 5-10 minutes TTL
                analytics.user:
                    adapter: cache.adapter.redis
                    provider: 'redis://user_analytics'
                    default_lifetime: 600 # 10 minutes
                    
                # Leaderboards - 1-2 minutes TTL
                analytics.leaderboard:
                    adapter: cache.adapter.redis
                    provider: 'redis://leaderboard'
                    default_lifetime: 120 # 2 minutes
                    
                # System configuration - 24 hours TTL
                app.config:
                    adapter: cache.adapter.redis
                    provider: 'redis://config'
                    default_lifetime: 86400 # 24 hours
                    
                # Real-time data - 30 seconds TTL
                analytics.realtime:
                    adapter: cache.adapter.redis
                    provider: 'redis://realtime'
                    default_lifetime: 30 # 30 seconds
                    
                # Fragment cache for templates
                app.fragments:
                    adapter: cache.adapter.redis
                    provider: 'redis://fragments'
                    default_lifetime: 900 # 15 minutes
                    
                # Query result cache
                cqrs.queries:
                    adapter: cache.adapter.redis
                    provider: 'redis://queries'
                    default_lifetime: 1800 # 30 minutes

services:
    # Redis connection factory
    App\Shared\Infrastructure\Cache\RedisConnectionFactory:
        arguments:
            $host: '%redis.host%'
            $port: '%redis.port%'
            $password: '%redis.password%'
            $clusterEnabled: '%redis.cluster_enabled%'
            $sentinelEnabled: '%redis.sentinel_enabled%'

    # Redis connections for different databases
    redis.connection.app:
        class: Predis\Client
        factory: ['@App\Shared\Infrastructure\Cache\RedisConnectionFactory', 'createConnection']
        arguments:
            $database: 0
            $alias: 'app'

    redis.connection.sessions:
        class: Predis\Client
        factory: ['@App\Shared\Infrastructure\Cache\RedisConnectionFactory', 'createConnection']
        arguments:
            $database: 1
            $alias: 'sessions'

    redis.connection.questions:
        class: Predis\Client
        factory: ['@App\Shared\Infrastructure\Cache\RedisConnectionFactory', 'createConnection']
        arguments:
            $database: 2
            $alias: 'questions'

    redis.connection.user_analytics:
        class: Predis\Client
        factory: ['@App\Shared\Infrastructure\Cache\RedisConnectionFactory', 'createConnection']
        arguments:
            $database: 3
            $alias: 'user_analytics'

    redis.connection.leaderboard:
        class: Predis\Client
        factory: ['@App\Shared\Infrastructure\Cache\RedisConnectionFactory', 'createConnection']
        arguments:
            $database: 4
            $alias: 'leaderboard'

    redis.connection.config:
        class: Predis\Client
        factory: ['@App\Shared\Infrastructure\Cache\RedisConnectionFactory', 'createConnection']
        arguments:
            $database: 5
            $alias: 'config'

    redis.connection.realtime:
        class: Predis\Client
        factory: ['@App\Shared\Infrastructure\Cache\RedisConnectionFactory', 'createConnection']
        arguments:
            $database: 6
            $alias: 'realtime'

    redis.connection.fragments:
        class: Predis\Client
        factory: ['@App\Shared\Infrastructure\Cache\RedisConnectionFactory', 'createConnection']
        arguments:
            $database: 7
            $alias: 'fragments'

    redis.connection.queries:
        class: Predis\Client
        factory: ['@App\Shared\Infrastructure\Cache\RedisConnectionFactory', 'createConnection']
        arguments:
            $database: 8
            $alias: 'queries'

when@test:
    framework:
        cache:
            app: cache.adapter.array
            pools:
                quiz.sessions:
                    adapter: cache.adapter.array
                quiz.questions:
                    adapter: cache.adapter.array
                analytics.user:
                    adapter: cache.adapter.array
                analytics.leaderboard:
                    adapter: cache.adapter.array
                app.config:
                    adapter: cache.adapter.array
                analytics.realtime:
                    adapter: cache.adapter.array
                app.fragments:
                    adapter: cache.adapter.array
                cqrs.queries:
                    adapter: cache.adapter.array