category: Bundles
questions:
    -
        question: 'In a modern Symfony application using Flex, where are bundles typically registered?'
        answers:
            - {value: 'config/bundles.php', correct: true}
            - {value: 'src/Kernel.php in the registerBundles() method', correct: false}
            - {value: 'composer.json under the "extra.symfony.bundles" key', correct: false}
            - {value: 'config/services.yaml', correct: false}
    -
        question: 'Which method in a bundle class is executed during container compilation to allow for service container modifications?'
        answers:
            - {value: 'build(ContainerBuilder $container)', correct: true}
            - {value: 'boot()', correct: false}
            - {value: '__construct()', correct: false}
            - {value: 'load(ContainerBuilder $container)', correct: false}
    -
        question: 'Which bundle is essential for providing core framework functionalities like routing, caching, and templating integration?'
        answers:
            - {value: 'FrameworkBundle', correct: true}
            - {value: 'SensioFrameworkExtraBundle', correct: false}
            - {value: 'TwigBundle', correct: false}
            - {value: 'DoctrineBundle', correct: false}
    -
        question: 'When defining bundle-specific configuration, which class is used to build the configuration tree?'
        answers:
            - {value: 'Symfony\Component\Config\Definition\Builder\TreeBuilder', correct: true}
            - {value: 'Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition', correct: false}
            - {value: 'Symfony\Component\Config\Definition\Configuration', correct: false}
            - {value: 'Symfony\Component\DependencyInjection\Loader\YamlFileLoader', correct: false}
    -
        question: 'Which of these are valid configuration node types in the Config component?'
        answers:
            - {value: 'scalar', correct: true}
            - {value: 'array', correct: true}
            - {value: 'enum', correct: true}
            - {value: 'boolean', correct: true}
            - {value: 'integer', correct: true}
            - {value: 'string', correct: false}
    -
        question: 'In a bundle''s configuration definition, which method marks a configuration key as mandatory?'
        answers:
            - {value: 'isRequired()', correct: true}
            - {value: 'cannotBeEmpty()', correct: false}
            - {value: 'defaultValue(null)', correct: false}
            - {value: 'required()', correct: false}
    -
        question: 'How can a bundle load its own service definitions?'
        answers:
            - {value: 'By creating a class that implements `ExtensionInterface` and loading a services file (e.g., services.xml) in the `load()` method.', correct: true}
            - {value: 'By placing a `services.yaml` file in the `config/` directory of the bundle.', correct: false}
            - {value: 'By adding a `services` key to the main `composer.json` file.', correct: false}
            - {value: 'Symfony automatically discovers and loads all `services.yaml` files in all bundles.', correct: false}
    -
        question: 'What is the correct signature for the `load()` method in a bundle''s `Extension` class?'
        answers:
            - {value: 'public function load(array $configs, ContainerBuilder $container)', correct: true}
            - {value: 'public function load(array $config, ContainerBuilder $container)', correct: false}
            - {value: 'public function load(ContainerBuilder $container, array $configs)', correct: false}
            - {value: 'public function load(ContainerBuilder $container)', correct: false}
    -
        question: 'How can you get a list of all registered bundles from the service container?'
        answers:
            - {value: 'By accessing the `kernel.bundles` parameter.', correct: true}
            - {value: 'By calling `$container->get(''bundle_guesser'')->getBundles()`.', correct: false}
            - {value: 'It is not possible to get the list of bundles from the container.', correct: false}
            - {value: 'By calling `$this->getParameter(''bundles'')` from a controller.', correct: false}
    -
        question: 'True or False: A bundle''s main class must extend `Symfony\Component\HttpKernel\Bundle\Bundle`.'
        answers:
            - {value: 'True', correct: true}
            - {value: 'False', correct: false}
    -
        question: 'While not mandatory for functionality, what file is commonly expected in a reusable bundle for documentation?'
        answers:
            - {value: 'README.md', correct: true}
            - {value: 'LICENSE', correct: true}
            - {value: 'docs/index.rst', correct: false}
            - {value: 'CONTRIBUTING.md', correct: true}
            - {value: 'services.yaml', correct: false}
