category: Security
questions:
    -
        question: 'What is the main component for handling security in Symfony?'
        answers:
            - {value: 'SecurityBundle', correct: true}
            - {value: 'FirewallBundle', correct: false}
            - {value: 'AccessControlBundle', correct: false}
            - {value: 'UserBundle', correct: false}
    -
        question: 'In Symfony, what is a "firewall" in the context of security?'
        answers:
            - {value: 'A part of the configuration that defines how to secure a set of URLs.', correct: true}
            - {value: 'A hardware device that protects the server.', correct: false}
            - {value: 'A service that filters incoming IP addresses.', correct: false}
            - {value: 'A component that prevents XSS attacks.', correct: false}
    -
        question: 'What is the recommended way to encode a user''s password in Symfony?'
        answers:
            - {value: 'Using the `PasswordHasher` component with a modern algorithm like Bcrypt or Argon2.', correct: true}
            - {value: 'Storing it in plain text.', correct: false}
            - {value: 'Using a simple hash like MD5 or SHA1.', correct: false}
            - {value: 'Encrypting it with a secret key.', correct: false}
    -
        question: 'What is the purpose of a "voter" in Symfony''s authorization system?'
        answers:
            - {value: 'To grant or deny access to resources based on custom business logic.', correct: true}
            - {value: 'To vote for the next features in Symfony.', correct: false}
            - {value: 'To authenticate users against a database.', correct: false}
            - {value: 'To manage user roles and permissions.', correct: false}
    -
        question: 'How does Symfony protect against Cross-Site Request Forgery (CSRF) attacks?'
        answers:
            - {value: 'By generating and validating a unique token for each form.', correct: true}
            - {value: 'By automatically escaping all output.', correct: false}
            - {value: 'By using a content security policy.', correct: false}
            - {value: 'By setting the `SameSite` attribute on cookies.', correct: false}
    -
        question: 'What is the `#[IsGranted]` attribute used for in a controller?'
        answers:
            - {value: 'To check for a specific role or permission before executing an action.', correct: true}
            - {value: 'To grant a user a new role.', correct: false}
            - {value: 'To check if the user is logged in.', correct: false}
            - {value: 'To define a new security role.', correct: false}
    -
        question: 'What is the purpose of the `access_control` section in `security.yaml`?'
        answers:
            - {value: 'To restrict access to URLs based on IP address, host, or roles.', correct: true}
            - {value: 'To define the password hashing algorithm.', correct: false}
            - {value: 'To configure the login form.', correct: false}
            - {value: 'To enable or disable the firewall.', correct: false}
    -
        question: 'What is a "User Provider" in Symfony?'
        answers:
            - {value: 'A class that knows how to fetch a user from a storage system (e.g., database, LDAP).', correct: true}
            - {value: 'A service that provides a list of all users.', correct: false}
            - {value: 'A form type for creating new users.', correct: false}
            - {value: 'A template for displaying user profiles.', correct: false}
    -
        question: 'Which component introduced in Symfony 5.2 simplifies creating authentication systems?'
        answers:
            - {value: 'The authenticator-based security system', correct: true}
            - {value: 'The Guard authentication system', correct: false}
            - {value: 'The SimplePreAuthenticator', correct: false}
            - {value: 'The FormLoginAuthenticator', correct: false}
    -
        question: 'How can you access the currently logged-in user object in a controller?'
        answers:
            - {value: 'By using the `#[CurrentUser]` attribute on an action argument.', correct: true}
            - {value: 'By calling `$this->getUser()`.', correct: true}
            - {value: 'By type-hinting `UserInterface $user` in the action method.', correct: true}
            - {value: 'By accessing `$this->container->get(''security.token_storage'')->getToken()->getUser()`.', correct: true}
