# Doctrine ORM mappings for DDD bounded contexts
doctrine:
    orm:
        mappings:
            # Legacy mapping for backward compatibility
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

            # Quiz Domain Mapping
            Quiz:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Quiz/Domain/Entity'
                prefix: 'App\Quiz\Domain\Entity'
                alias: Quiz

            # Analytics Domain Mapping
            Analytics:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Analytics/Domain/Entity'
                prefix: 'App\Analytics\Domain\Entity'
                alias: Analytics

            # User Domain Mapping
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain/Entity'
                prefix: 'App\User\Domain\Entity'
                alias: User

            # Shared Domain Mapping
            Shared:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Domain/Entity'
                prefix: 'App\Shared\Domain\Entity'
                alias: Shared